sudo: false

before_install:
  - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  - npm install -g grunt-cli

install:
  - bundle install
  - npm install grunt grunt-html --save-dev

script:
  - rake ci

# environment
language: ruby
rvm:
  - "2.2.3"
jdk:
  - oraclejdk8
dist: precise

before_deploy: if [[ ${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH} != master ]]; then
    bundle exec jekyll clean && bundle exec jekyll build --baseurl /api/${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH};
  else
    bundle exec jekyll clean && bundle exec jekyll build;
  fi

deploy:
  - provider: s3
    access_key_id:
      secure: "aYJibzw6wdmoekRn8MR73NSu3DZU1kaS/cImMZ527X2BWNDsWSey4af4vLAJ+Vc1vuFqV7FW5dpj2cFnAVN/feVrKt5elqxCajfDtWgHSiY3HH/9GUPEFCsm3EWNpyoMpEfcsKPf+DjOhAGyOCwE+zkXFWMhxXxFDV1khgwfhd8="
    secret_access_key:
      secure: "WnfqGrUQjlsHndutcdUV/z7vIDnsTS+eJxbFI+kVJw7RdcPuzf1nEDUbiVy7W52PwsfH5EVwuPEiyOEYQqDvQg3tzQSuZc47SSMt94+K6QrkUTGxoihG5xfdhoR/puSX+Yd/UsK7y1jLfe+Kx/TXvgKvN0VGUe6z9JXTUzcuY64="
    bucket: iiif-api-website
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    on:
      branch: master
  - provider: s3
    access_key_id:
      secure: "WJBKJiYRQkOO5nveEVFVOADt34U3K4vK6PZ8gIATfRdqyD9cPkiEtajmB7yPw7Hs4NHxyfELJ32TYLLr4jhr6krf/a0O/1ji76rlOC7Rfcio7kXqxjF5P/wuVK34evN+PGNVb4kkoMAOocW/02yxP6Xfyx1VhofEpZcrdtjUibo="
    secret_access_key:
      secure: "A6Py+gxHItulsfd6qxBA5o6vpHD00f836oiFfhp667OvE+QLQiaulMljA3xzEdb5Y0N0+C+Lc8S+58ASbJzRa4TKmNUPWQ3NRIL8zgPQhUWllrrV+I+NBA3jXkdoXHjDr9CK/Gj16f25VgHUo9UWpTfsHaISLWrQhyE91EwJZLs="
    bucket: preview.iiif.io
    skip_cleanup: true
    acl: public_read
    region: us-east-1
    local_dir: _site
    upload-dir: "api/$TRAVIS_BRANCH"
    on:
      all_branches: true
      condition: "$TRAVIS_BRANCH != master"

notifications:
  email:
    recipients:
      - "azaroth42@gmail.com"
      - "blalbrit@stanford.edu"
      - "jpstroop@gmail.com"
      - "michael.appleby@yale.edu"
      - "simeon.warner@gmail.com"
      - "glen.robson@gmail.com"
    on_success: "change"
    on_failure: "change"
