name: IIIF | International Image Interoperability Framework
markdown: kramdown
highlighter: pygments
source: source

permalink: /news/:year/:month/:day/:title

kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: nil
    coderay_css: class

image_api:
  latest:
    major: 2
    minor: 0
    patch: 0
presentation_api:
  latest:
    major: 2
    minor: 0
    patch: 0
shared_canvas:
  latest:
    major: 1
    minor: 0
    patch: 0

