markdown: kramdown
highlighter: pygments
source: source
safe: false
permalink: /news/:year/:month/:day/:title/

kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..6
  use_coderay: true

  coderay:
    coderay_wrap: div
    coderay_line_numbers: nil
    coderay_css: class

image_api:
  latest:
    major: 2
    minor: 0
    patch: 0
presentation_api:
  latest:
    major: 2
    minor: 0
    patch: 0
shared_canvas:
  latest:
    major: 1
    minor: 0
    patch: 0
search_api:
  latest:
    major: 0
    minor: 9
    patch: 1
auth_api:
  latest:
    major: 0
    minor: 9
    patch: 1
    