markdown: kramdown
source: source
safe: false
permalink: /news/:year/:month/:day/:title/

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..4

image_api:
  draft:
    major: 3
    minor: 0
    patch: 0
  stable:
    major: 2
    minor: 1
    patch: 1
presentation_api:
  draft:
    major: 3
    minor: 0
    patch: 0
  stable:
    major: 2
    minor: 1
    patch: 1
shared_canvas:
  draft:
    major: 1
    minor: 0
    patch: 0
  stable:
    major: 1
    minor: 0
    patch: 0
search_api:
  draft:
    major: 1
    minor: 0
    patch: 0
  stable:
    major: 1
    minor: 0
    patch: 0
auth_api:
  draft:
    major: 1
    minor: 0
    patch: 0
  stable:
    major: 1
    minor: 0
    patch: 0
defaults:
  -
    scope:
      path: ""
    values:
      webprefix: "https://iiif.io"
