markdown: kramdown
source: source
safe: false
permalink: /news/:year/:month/:day/:title/

gems:
  - jekyll-sitemap
  - jekyll-redirect-from

kramdown:
  input: GFM
  parse_block_html: true
  toc_levels: 2..4
  enable_coderay: true
  syntax_highlighter: rouge

  coderay:
    coderay_wrap: div
    coderay_line_numbers: nil
    coderay_css: class

image_api:
  latest:
    major: 2
    minor: 1
    patch: 1
presentation_api:
  latest:
    major: 2
    minor: 1
    patch: 0
shared_canvas:
  latest:
    major: 1
    minor: 0
    patch: 0
search_api:
  latest:
    major: 1
    minor: 0
    patch: 0
auth_api:
  latest:
    major: 0
    minor: 9
    patch: 1
